# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import pandas as pd
import pyqtgraph as pg
import sys
from datetime import datetime, date, timedelta
from model import PandasModel
from os import path
from pyqtgraph import PlotWidget, plot
from PyQt5 import QtCore
from PyQt5 import QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QMainWindow
from PyQt5.uic import loadUiType

from PyQt5 import QtCore, QtGui, QtWidgets

def resource_path(relative_path):
    base_path = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(340, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setEnabled(True)
        self.groupBox.setMinimumSize(QtCore.QSize(320, 132))
        self.groupBox.setMaximumSize(QtCore.QSize(320, 132))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.load_btn = QtWidgets.QPushButton(self.groupBox)
        self.load_btn.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.load_btn.setObjectName("load_btn")
        self.verticalLayout_2.addWidget(self.load_btn)
        self.validation_btn = QtWidgets.QPushButton(self.groupBox)
        self.validation_btn.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.validation_btn.setObjectName("validation_btn")
        self.verticalLayout_2.addWidget(self.validation_btn)
        self.calculate_btn = QtWidgets.QPushButton(self.groupBox)
        self.calculate_btn.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.calculate_btn.setObjectName("calculate_btn")
        self.verticalLayout_2.addWidget(self.calculate_btn)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setMinimumSize(QtCore.QSize(320, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(320, 140))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.termocouple_number = QtWidgets.QLabel(self.groupBox_2)
        self.termocouple_number.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.termocouple_number.setText("")
        self.termocouple_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.termocouple_number.setObjectName("termocouple_number")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.termocouple_number)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.start_time = QtWidgets.QLabel(self.groupBox_2)
        self.start_time.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.start_time.setText("")
        self.start_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.start_time.setObjectName("start_time")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.start_time)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.stop_time = QtWidgets.QLabel(self.groupBox_2)
        self.stop_time.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.stop_time.setText("")
        self.stop_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stop_time.setObjectName("stop_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.stop_time)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.time_delta = QtWidgets.QLabel(self.groupBox_2)
        self.time_delta.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.time_delta.setText("")
        self.time_delta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_delta.setObjectName("time_delta")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.time_delta)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setMinimumSize(QtCore.QSize(320, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(320, 16777215))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.validation_label = QtWidgets.QLabel(self.groupBox_3)
        self.validation_label.setText("")
        self.validation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.validation_label.setObjectName("validation_label")
        self.verticalLayout_3.addWidget(self.validation_label)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.addWidget(self.frame)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(600, 0))
        self.tabWidget.setStyleSheet("font: 14pt \"Century Gothic\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.table = QtWidgets.QTableView(self.tab)
        self.table.setObjectName("table")
        self.verticalLayout_4.addWidget(self.table)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.graphics_view = PlotWidget(self.tab_2)
        self.graphics_view.setObjectName("graphics_view")
        self.verticalLayout_5.addWidget(self.graphics_view)
        self.partial_f0_box = QtWidgets.QGroupBox(self.tab_2)
        self.partial_f0_box.setTitle("")
        self.partial_f0_box.setObjectName("partial_f0_box")
        self.gridLayout = QtWidgets.QGridLayout(self.partial_f0_box)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.partial_f0_box)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.partial_f0_box)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.T_total = QtWidgets.QLabel(self.groupBox_5)
        self.T_total.setAlignment(QtCore.Qt.AlignCenter)
        self.T_total.setObjectName("T_total")
        self.verticalLayout_6.addWidget(self.T_total)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.buttons()

    def buttons(self):
        self.load_btn.clicked.connect(self.open_file)
        self.validation_btn.setEnabled(False)
        self.validation_btn.clicked.connect(self.validate_data)
        self.calculate_btn.setEnabled(False)
        self.calculate_btn.clicked.connect(self.calculate_data)

    def open_file(self):
        global df
        try:
            file_name, _ = QtWidgets.QFileDialog.getOpenFileName(self, "Open File", "", "Excel (*.xlsx)")
            df = pd.read_excel(resource_path(file_name))
            model = PandasModel(df)
            self.table.setModel(model)
            self.termocouple_number.setText(str(len(df.columns) - 1))
            self.validation_btn.setEnabled(True)
            self.calculate_btn.setEnabled(False)
        except FileNotFoundError:
            pass

    @staticmethod
    def format_time(time):
        minutes = int(time)
        seconds = int((time * 60) % 60)
        return f"{minutes}\'{seconds}\'\'"

    def validate_data(self):
        global new_df
        sterile_hold_min_temp_list = []
        sterile_hold_elapsed_time = {}
        for column in range(1, len(df.columns)):
            sterile_hold_min_temp_row = (df[f'Temp_{column}'].values >= 121.0).argmax()
            sterile_hold_max_temp_row = (df[f'Temp_{column}'].values >= 123.0).argmax()
            sterile_hold_min_time = df.at[sterile_hold_min_temp_row, 'TIME']
            sterile_hold_max_time = df.at[sterile_hold_max_temp_row, 'TIME']
            time_difference = datetime.combine(date.today(), sterile_hold_max_time) \
                              - datetime.combine(date.today(), sterile_hold_min_time)
            sterile_hold_min_temp_row = (df[f'Temp_{column}'].values >= 121.0).argmax()
            sterile_hold_min_temp_list.append(sterile_hold_min_temp_row)
            sterile_hold_elapsed_time[f'Temp_{column}'] = str(
                timedelta(seconds=pd.Timedelta(time_difference).seconds))

        last_termocouple_temp_121_row = max(range(len(sterile_hold_min_temp_list)),
                                            key=sterile_hold_min_temp_list.__getitem__)
        new_df = pd.DataFrame(df)[sterile_hold_min_temp_list[last_termocouple_temp_121_row]:
                                  sterile_hold_min_temp_list[last_termocouple_temp_121_row] + 187].copy(deep=True)
        model = PandasModel(new_df)
        self.table.setModel(model)
        temp_df = new_df.drop(['TIME'], axis=1)
        if (temp_df.values >= 121.0).all() and (temp_df.values <= 123.0).all():
            self.validation_label.setStyleSheet(
                'background-color: rgb(75, 225, 0);color: rgb(20, 125, 0);font: 75 16pt "Century Gothic";')
            self.validation_label.setText('Sterile Hold valid!')
        if (temp_df.values < 121.0).any():
            self.validation_label.setStyleSheet(
                'background-color: rgb(255, 0, 0);color: rgb(255, 255, 255);font: 75 16pt "Century Gothic";')
            self.validation_label.setText('Sterile Hold invalid!')
        self.start_time.setText(str(new_df.iloc[0]['TIME']))
        self.stop_time.setText(str(new_df.iloc[186]['TIME']))
        delta_time = datetime.combine(date.today(), new_df.iloc[186]['TIME']) - datetime.combine(date.today(),
                                                                                                 new_df.iloc[0][
                                                                                                     'TIME'])
        if delta_time == timedelta(minutes=15, seconds=30):
            self.time_delta.setStyleSheet('font: 75 16pt "Century Gothic";color: rgb(20, 125, 0);')
        else:
            self.time_delta.setStyleSheet('font: 75 16pt "Century Gothic";color: rgb(255, 0, 0);')
        self.time_delta.setText(str(delta_time))
        self.calculate_btn.setEnabled(True)

    def calculate_data(self):
        self.graphics_view.clear()
        colors = ['#FF0000', '#FF8000', '#FFFF00', '#80FF00', '#00FF00', '#00FF80', '#00FFFF', '#0080FF', '#0000FF',
                  '#7F00FF', '#FF00FF', '#FF007F']
        x_axis = new_df['TIME'].index.tolist()
        self.graphics_view.getPlotItem().setLabel('bottom', "Time index")
        self.graphics_view.getPlotItem().setLabel('left', "Temperature")
        self.graphics_view.getPlotItem().addLegend()
        self.graphics_view.getPlotItem().addLine(y=121.0, pen=pg.mkPen(style=QtCore.Qt.DotLine, color='#FFFFFF'))
        self.graphics_view.getPlotItem().addLine(y=123.0, pen=pg.mkPen(style=QtCore.Qt.DotLine, color='#FFFFFF'))
        for column in range(1, len(df.columns)):
            y_axis = new_df[f'Temp_{column}'].values.tolist()
            self.graphics_view.plot(x_axis, y_axis, pen=pg.mkPen(color=colors[column - 1]), name=f'T{column}')
        f_list = []
        for column in range(1, len(df.columns)):
            f0 = 0
            for row in range(1, len(x_axis)):
                f0 += 0.08333333 * (10 ** ((new_df.iloc[row][f'Temp_{column}'] - 121.0) / 6.0))
            f_list.append(self.format_time(f0))

        col = row = 0
        for n in range(len(f_list)):
            self.label_2 = QtWidgets.QLabel(self.partial_f0_box)
            self.label_2.setObjectName("label_2")
            self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

            self.label = QtWidgets.QLabel(self.partial_f0_box)
            self.label.setStyleSheet(f"background-color: {colors[n - 1]};")
            self.label.setText(f"[T{n}] F0={f_list[n - 1]}")
            self.label.setAlignment(QtCore.Qt.AlignCenter)
            self.label.setObjectName(f"label_{n}")
            self.partial_f0_box.addWidget(self.label, col, row, 1, 1)
            row += 1
            if row == 4:
                row = 0
                col += 1

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_btn.setText(_translate("MainWindow", "Load File"))
        self.validation_btn.setText(_translate("MainWindow", "Validate"))
        self.calculate_btn.setText(_translate("MainWindow", "Post-Calculate"))
        self.label.setText(_translate("MainWindow", "No. of termocouples:"))
        self.label_3.setText(_translate("MainWindow", "T1:"))
        self.label_5.setText(_translate("MainWindow", "T2:"))
        self.label_7.setText(_translate("MainWindow", "ΔT = T2 - T1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Data"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.T_total.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "\"F_zero\" Post-Calculation"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
