# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 414)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")

        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet(f"background-color: rgb(255, 0, 4);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setStyleSheet(f"background-color: rgb(255, 188, 140);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setStyleSheet(f"background-color: rgb(64, 255, 43);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setStyleSheet(f"background-color: rgb(147, 70, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setStyleSheet(f"background-color: rgb(255, 245, 220);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setStyleSheet(f"background-color: rgb(73, 67, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setStyleSheet(f"background-color: rgb(22, 22, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setStyleSheet(f"background-color: rgb(22, 22, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")

        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setStyleSheet(f"background-color: rgb(22, 22, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")

        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # widget_list = [[self.label, 1, 0, 1, 1], [self.label_2, 1, 1, 1, 1]]

        self.labels = [self.label, self.label_2, self.label_3, self.label_4, self.label_5, self.label_6, self.label_7, self.label_8, self.label_9]
        col = row = 0
        col = row = 0
        for label in self.labels:
            self.gridLayout.addWidget(label, col, row, 1, 1)
            row += 1
            if row == 4:
                row = 0
                col += 1

        for label in self.labels:
            self.gridLayout.addWidget(label, col, row, 1, 1)
            row += 1
            if row == 4:
                row = 0
                col += 1

        # self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        # self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        # self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        # self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        # self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        # self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "A1"))
        self.label_4.setText(_translate("MainWindow", "B1"))
        self.label_3.setText(_translate("MainWindow", "A3"))
        self.label_2.setText(_translate("MainWindow", "A2"))
        self.label_5.setText(_translate("MainWindow", "C1"))
        self.label_6.setText(_translate("MainWindow", "B2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
